#!/usr/bin/env node
import{createAccount,createClient}from'../frontend/node_modules/genlayer-js/dist/index.js';import{studioDevnet}from'../frontend/node_modules/genlayer-js/dist/chains/index.js';
const CONTRACT=process.argv[2],EXECUTOR=process.argv[3];if(!/^0x[0-9a-fA-F]{40}$/.test(CONTRACT||'')||!/^0x[0-9a-fA-F]{40}$/.test(EXECUTOR||''))throw Error('Usage: node scripts/run_live_e2e.mjs <scope-sentinel> <guarded-executor>');const chain={...studioDevnet,id:61997,name:'GenLayer Studio Next',rpcUrls:{default:{http:['https://studio-next.genlayer.com/api']}}};
function hidden(prompt){return new Promise((resolve,reject)=>{process.stdout.write(prompt);process.stdin.setRawMode(true);process.stdin.resume();process.stdin.setEncoding('utf8');let value='';const done=()=>{process.stdin.off('data',onData);process.stdin.setRawMode(false);process.stdin.pause()};const onData=chunk=>{for(const ch of chunk){if(ch==='\u0003'){done();reject(Error('Interrupted'));return}if(ch==='\r'||ch==='\n'){done();process.stdout.write('\n');resolve(value.trim());return}if(ch==='\u007f'||ch==='\b')value=value.slice(0,-1);else value+=ch}};process.stdin.on('data',onData)})}
async function signer(label){const key=await hidden(`${label} private key (hidden): `),account=createAccount(key.startsWith('0x')?key:`0x${key}`);return{account,client:createClient({chain,account})}}
const creator=await signer('proposal creator wallet A'),reviewer=await signer('independent reviewer wallet B');if(creator.account.address.toLowerCase()===reviewer.account.address.toLowerCase())throw Error('Distinct wallets required.');console.log(`actors=${creator.account.address},${reviewer.account.address}`);
const readAt=(s,address,name,args=[])=>s.client.readContract({address,functionName:name,args,stateStatus:'finalized',jsonSafeReturn:true});const read=(s,name,args=[])=>readAt(s,CONTRACT,name,args);
async function write(s,label,name,args,validators=300n){const fees=await s.client.estimateTransactionFees({leaderTimeunitsAllocation:300n,validatorTimeunitsAllocation:validators});const hash=await s.client.writeContract({account:s.account,address:CONTRACT,functionName:name,args,value:0n,fees:{distribution:fees.distribution,feeValue:fees.feeValue}});console.log(`${label}.submitted=${hash}`);const receipt=await s.client.waitForTransactionReceipt({hash,waitUntil:'finalized',interval:3000,retries:600,fullTransaction:false});const tx=await s.client.getTransaction({hash}),consensus=tx.result_name||tx.result||'UNKNOWN';if(receipt?.txExecutionResultName&&receipt.txExecutionResultName!=='FINISHED_WITH_RETURN')throw Error(`${label} execution=${receipt.txExecutionResultName}`);if(!['AGREE','MAJORITY_AGREE'].includes(String(consensus)))throw Error(`${label} consensus=${consensus}`);console.log(`${label}.finalized=${hash} execution=${receipt?.txExecutionResultName||'unknown'} consensus=${consensus}`);return hash}
const check=(ok,label,data)=>{if(!ok)throw Error(`${label}: ${JSON.stringify(data)}`);console.log(`${label}.readback=${JSON.stringify(data)}`)};
const epoch=Math.floor(Date.now()/1000);const action=(amount,recipient='0x'+'b'.repeat(40),nonce=1)=>JSON.stringify([{executor:EXECUTOR.toLowerCase(),target:'0x'+'a'.repeat(40),chain_id:61997,calldata:'0x12345678'+'00'.repeat(32),value:0,asset:'NATIVE',recipient,amount,nonce,valid_after:epoch-3600,valid_until:epoch+86400}]);
const base='Fund the open-source wallet security audit with 1000 units sent to the named audit collective after delivery of the final report. The collective may only perform the scoped wallet audit.';
const revised='Fund the open-source wallet security audit with 1200 units sent to the named audit collective after delivery of the final report. The increase covers an added mobile-wallet review.';
const summary='Discloses the increase from 1000 to 1200 units and the added mobile-wallet review scope and execution amount.';
const hiddenText='Fund the ecosystem security program with 1500 units sent to a new recipient. The recipient may spend the allocation on any security-related activity it selects.';
const protocol=await read(creator,'get_protocol'),executorInfo=await readAt(creator,EXECUTOR,'get_info'),initial=await read(creator,'get_counts');check(protocol.name==='ScopeSentinel'&&protocol.version===2&&protocol.execution_boundary==='FINALIZED_CROSS_CONTRACT_MESSAGE','protocol',protocol);check(executorInfo.guard.toLowerCase()===CONTRACT.toLowerCase(),'executor bound to guard',executorInfo);check(Number(initial.proposals)===0&&Number(initial.revisions)===0&&Number(initial.assessments)===0&&Number(initial.executions)===0,'clean deployment required',initial);
if(Number(initial.proposals)===0)await write(creator,'happy_create_baseline','create_proposal',['Wallet audit mandate',base,action(1000)]);else console.log('happy_create_baseline.resumed=already_finalized');let p1=await read(creator,'get_proposal',[1]),r1=await read(creator,'get_revision',[1]);check(p1.creator.toLowerCase()===creator.account.address.toLowerCase()&&r1.status==='ACTIVE'&&Number(p1.revision)===1,'baseline active',{proposal:p1,revision:r1});
await write(reviewer,'happy_propose_revision','propose_revision',[1,1,r1.text_digest,revised,summary,action(1200),1]);let r2=await read(creator,'get_revision',[2]);check(r2.status==='REVISION_PROPOSED'&&r2.diff_fields.includes('AMOUNT'),'revision bound with action diff',r2);
const beforeStale=JSON.stringify(r2);await write(reviewer,'stale_assessment_rejected','assess_revision',[2,1]);r2=await read(creator,'get_revision',[2]);check(JSON.stringify(r2)===beforeStale,'stale assessment no mutation',r2);
await write(reviewer,'happy_assess_revision','assess_revision',[2,2],600n);r2=await read(creator,'get_revision',[2]);let a1=await read(creator,'get_assessment',[1]);check(r2.status==='CERTIFIED'&&a1.result==='CERTIFIED'&&a1.action_diff_disclosed===true,'fully disclosed certified',{revision:r2,assessment:a1});
const beforeUnauthorized=JSON.stringify(await read(creator,'get_proposal',[1]));await write(reviewer,'unauthorized_activation_rejected','activate_revision',[1,2,2]);check(JSON.stringify(await read(creator,'get_proposal',[1]))===beforeUnauthorized,'unauthorized activation no mutation',await read(creator,'get_proposal',[1]));
await write(creator,'happy_activate_revision','activate_revision',[1,2,2]);p1=await read(creator,'get_proposal',[1]);r1=await read(creator,'get_revision',[1]);r2=await read(creator,'get_revision',[2]);const queued=await read(creator,'get_execution',[1]);check(p1.active_revision_id===2&&p1.revision===3&&r1.status==='SUPERSEDED'&&r2.status==='ACTIVE'&&queued.status==='EXECUTION_QUEUED','atomic activation',{proposal:p1,parent:r1,active:r2,queued});
let downstream={};for(let i=0;i<30;i++){downstream=await readAt(creator,EXECUTOR,'get_execution',[1]);if(downstream.status==='EXECUTED')break;await new Promise(r=>setTimeout(r,4000))}const allocation=await readAt(creator,EXECUTOR,'get_allocation',['0x'+'b'.repeat(40)]);check(downstream.status==='EXECUTED'&&Number(allocation)===1200,'downstream execution effect',{downstream,allocation});
const terminal=JSON.stringify({p:p1,r:r2});await write(creator,'activation_replay_rejected','activate_revision',[1,2,3]);check(JSON.stringify({p:await read(creator,'get_proposal',[1]),r:await read(creator,'get_revision',[2])})===terminal,'replay no mutation',{proposal:await read(creator,'get_proposal',[1]),revision:await read(creator,'get_revision',[2])});
await write(creator,'hidden_create_baseline','create_proposal',['Ecosystem security mandate',base,action(1000,'0x'+'b'.repeat(40),2)]);const p2=await read(creator,'get_proposal',[2]),r3=await read(creator,'get_revision',[3]);
await write(reviewer,'hidden_propose_revision','propose_revision',[2,3,r3.text_digest,hiddenText,'Formatting and wording cleanup only; no material changes are declared.',action(1500,'0x'+'c'.repeat(40),3),1]);
await write(reviewer,'hidden_assess_revision','assess_revision',[4,2],600n);const r4=await read(creator,'get_revision',[4]),a2=await read(creator,'get_assessment',[2]);check(r4.status==='BLOCKED'&&a2.result==='BLOCKED'&&r4.diff_fields.includes('RECIPIENT')&&r4.diff_fields.includes('AMOUNT'),'hidden change blocked',{revision:r4,assessment:a2});
const blockedBefore=JSON.stringify(await read(creator,'get_proposal',[2]));await write(creator,'blocked_activation_rejected','activate_revision',[2,4,2]);check(JSON.stringify(await read(creator,'get_proposal',[2]))===blockedBefore,'blocked activation no mutation',await read(creator,'get_proposal',[2]));
const counts=await read(creator,'get_counts'),finalExecutor=await readAt(creator,EXECUTOR,'get_info');check(Number(counts.proposals)===2&&Number(counts.revisions)===4&&Number(counts.assessments)===2&&Number(counts.executions)===1&&Number(finalExecutor.execution_count)===1&&Number(finalExecutor.total_authorized)===1200,'final counts',{guard:counts,executor:finalExecutor});console.log('e2e.result=PASS');
